FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.ts ./

RUN npm ci

COPY . .

# Generate prisma client
RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
